### ISSUE TITLE
Stop listing all songs on home page

### ISSUE THREAD

**Issue by PeterBell** [smithWEBtek/piano-cms#3]

**Comment by PeterBell** [comment]
Remove the listing from the home page and the variable from the controller. Just have a link to list all songs to go to the /song route and implement there.

**Comment by smithWEBtek** [comment]
@PeterBell 

Moved the form to a new page:  songs/delete.html.erb 
Removed the @all_songs = Song.all.order(:name)  variable, and put it in: get '/songs/destroy'

**Comment by smithWEBtek** [comment]
Fixed with #8
